require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Admin::TopicsController do

  # This should return the minimal set of attributes required to create a valid
  # Admin::Topic. As you add validations to Admin::Topic, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Admin::TopicsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all admin_topics as @admin_topics" do
      topic = Admin::Topic.create! valid_attributes
      get :index, {}, valid_session
      assigns(:admin_topics).should eq([topic])
    end
  end

  describe "GET show" do
    it "assigns the requested topic as @topic" do
      topic = Admin::Topic.create! valid_attributes
      get :show, {:id => topic.to_param}, valid_session
      assigns(:topic).should eq(topic)
    end
  end

  describe "GET new" do
    it "assigns a new topic as @topic" do
      get :new, {}, valid_session
      assigns(:topic).should be_a_new(Admin::Topic)
    end
  end

  describe "GET edit" do
    it "assigns the requested topic as @topic" do
      topic = Admin::Topic.create! valid_attributes
      get :edit, {:id => topic.to_param}, valid_session
      assigns(:topic).should eq(topic)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Admin::Topic" do
        expect {
          post :create, {:topic => valid_attributes}, valid_session
        }.to change(Admin::Topic, :count).by(1)
      end

      it "assigns a newly created topic as @topic" do
        post :create, {:topic => valid_attributes}, valid_session
        assigns(:topic).should be_a(Admin::Topic)
        assigns(:topic).should be_persisted
      end

      it "redirects to the created topic" do
        post :create, {:topic => valid_attributes}, valid_session
        response.should redirect_to(Admin::Topic.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved topic as @topic" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Topic.any_instance.stub(:save).and_return(false)
        post :create, {:topic => {}}, valid_session
        assigns(:topic).should be_a_new(Admin::Topic)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Topic.any_instance.stub(:save).and_return(false)
        post :create, {:topic => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested topic" do
        topic = Admin::Topic.create! valid_attributes
        # Assuming there are no other admin_topics in the database, this
        # specifies that the Admin::Topic created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Admin::Topic.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => topic.to_param, :topic => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested topic as @topic" do
        topic = Admin::Topic.create! valid_attributes
        put :update, {:id => topic.to_param, :topic => valid_attributes}, valid_session
        assigns(:topic).should eq(topic)
      end

      it "redirects to the topic" do
        topic = Admin::Topic.create! valid_attributes
        put :update, {:id => topic.to_param, :topic => valid_attributes}, valid_session
        response.should redirect_to(topic)
      end
    end

    describe "with invalid params" do
      it "assigns the topic as @topic" do
        topic = Admin::Topic.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Topic.any_instance.stub(:save).and_return(false)
        put :update, {:id => topic.to_param, :topic => {}}, valid_session
        assigns(:topic).should eq(topic)
      end

      it "re-renders the 'edit' template" do
        topic = Admin::Topic.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Topic.any_instance.stub(:save).and_return(false)
        put :update, {:id => topic.to_param, :topic => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested topic" do
      topic = Admin::Topic.create! valid_attributes
      expect {
        delete :destroy, {:id => topic.to_param}, valid_session
      }.to change(Admin::Topic, :count).by(-1)
    end

    it "redirects to the admin_topics list" do
      topic = Admin::Topic.create! valid_attributes
      delete :destroy, {:id => topic.to_param}, valid_session
      response.should redirect_to(admin_topics_url)
    end
  end

end
